[tool.poetry]
name = "splunk_add_on_ucc_framework"
version = "0.1.0"
description = ""
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]

[tool.poetry.dependencies]
python = "^3.7"
solnlib = '>=2.0.8a3'
splunk-sdk = "^1.6"
jinja2 = "^2"
mako= "^1"
munch= "^2"
lxml = "^4.5"

[tool.poetry.dev-dependencies]
pytest = "^6"

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry.scripts]
ucc-gen = "splunk_add_on_ucc_framework:main"