[tool.poetry]
name = "splunk_add_on_ucc_framework"
version = "0.1.0"
description = ""
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]
exclude = ["splunk_add_on_ucc_framework/UCC-UI-lib", "build.py"]

[tool.poetry.dependencies]
python = "^3.7"
solnlib = '^2.1'
splunk-sdk = "^1.6"
jinja2 = "^2"
mako= "^1"
munch= "^2"
lxml = "^4.3"
future = "^0"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-splunk-addon = "^1.3"
lovely-pytest-docker = "^0"
[tool.poetry.scripts]
ucc-gen="splunk_add_on_ucc_framework:main"
build-ucc="build:build_ucc"
install-libs="splunk_add_on_ucc_framework:install_requirements"
[build-system]
requires=["setuptools >= 40.6.0", "wheel"]
build-backend="setuptools.build_meta"

