version: 2.1
orbs:
  go: circleci/go@0.2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            npm install -g bower
            
      - run:
          name: Install
          command: |
            source $HOME/.poetry/env
            export PATH=~/.npm-global/bin:$PATH
            poetry install
            poetry run build-ucc
            poetry build
      - store_artifacts:
          path: /tmp/workspace/

workflows:
  version: 2
  build_test:
    jobs:
      - build
