version: 2.1
orbs:
  go: circleci/go@0.2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - run:
          name: Install Tools
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            npm install -g bower

      - run:
          name: Build
          command: |
            source $HOME/.poetry/env
            export PATH=~/.npm-global/bin:$PATH
            poetry install
            poetry run build-ucc
            poetry build
            poetry run ucc-gen --source tests/data/package --config tests/data/globalConfig.json
      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - ~/.poetry
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist
            - output

workflows:
  version: 2
  build_test:
    jobs:
      - build
